codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 68%
        threshold: 1%
    patch:
      default:
        target: 80%

flag_management:
  default_rules:
    carryforward: true

ignore:
  - "test/"
  - "examples/"
  - "python/"
  - "tools/"
  - "docs/"
  - "docker/"
