// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This is used for execute json file generated by msccl scheduler

#include "executor.hpp"

namespace mscclpp {

void Executor::Impl::launchKernel() {
}

}  // namespace mscclpp
