parameters:
- name: subscription
  type: string
- name: vmssName
  type: string
- name: perfBaselineFile
  type: string
  default: 'test/deploy/perf_ndmv4.jsonl'
- name: gpuArch
  type: string
- name: containerName
  type: string
  default: 'sglang-mscclpp-test'

steps:
- template: deploy.yml
  parameters:
    subscription:     ${{ parameters.subscription }}
    vmssName:         ${{ parameters.vmssName }}
    gpuArch:          ${{ parameters.gpuArch }}
    deployArgs:       'single-node-test false cuda' # not sure if this should be IB or not
    containerName:    ${{ parameters.containerName }}

# - template: run-remote-task.yml
#   parameters:
#     name: InstallMscclpp
#     displayName: Install mscclpp
#     runRemoteArgs: '--container sglang-mscclpp-test'
#     remoteScript: |
#       cd mscclpp
#       pip install .
#       pip install -r ./python/requirements_cuda12.txt

- template: run-remote-task.yml
  parameters:
    name: InstallSGLang
    displayName: Install SGLang
    runRemoteArgs: '--container sglang-mscclpp-test'
    remoteScript: |
      git clone -b release/v0.5.7 https://github.com/caiomcbr/sglang.git
      cd sglang
      pip install --upgrade pip
      pip install -e "python"

- template: run-remote-task.yml
  parameters:
    name: RunSGLangTestBatchSize1
    displayName: Run SGLang Test Batch Size 1
    runRemoteArgs: '--container sglang-mscclpp-test'
    remoteScript: |
      python -m sglang.bench_one_batch --model-path Qwen/Qwen3-8B --batch 1 --input-len 256 --output-len 256 --tp-size 8 --disable-custom-all-reduce --enable-mscclpp 

- template: run-remote-task.yml
  parameters:
    name: RunSGLangTestBatchSize2
    displayName: Run SGLang Test Batch Size 2
    runRemoteArgs: '--container sglang-mscclpp-test'
    remoteScript: |
      python -m sglang.bench_one_batch --model-path Qwen/Qwen3-8B --batch 2 --input-len 256 --output-len 256 --tp-size 8 --disable-custom-all-reduce --enable-mscclpp 

- template: run-remote-task.yml
  parameters:
    name: RunSGLangTestBatchSize32
    displayName: Run SGLang Test Batch Size 32
    runRemoteArgs: '--container sglang-mscclpp-test'
    remoteScript: |
      python -m sglang.bench_one_batch --model-path Qwen/Qwen3-8B --batch 32 --input-len 256 --output-len 256 --tp-size 8 --disable-custom-all-reduce --enable-mscclpp 

- template: run-remote-task.yml
  parameters:
    name: RunSGLangTestBatchSize64
    displayName: Run SGLang Test Batch Size 64
    runRemoteArgs: '--container sglang-mscclpp-test'
    remoteScript: |
      python -m sglang.bench_one_batch --model-path Qwen/Qwen3-8B --batch 64 --input-len 256 --output-len 256 --tp-size 8 --disable-custom-all-reduce --enable-mscclpp 


- template: run-remote-task.yml
  parameters:
    name: RunSGLangTestAllReduce
    displayName: Run SGLang Test All Reduce
    runRemoteArgs: '--container sglang-mscclpp-test'
    remoteScript: |
      export WORLD_SIZE=1
      export RANK=0
      export MASTER_ADDR=127.0.0.1
      export MASTER_PORT=12345

      cd sglang

      torchrun --nproc_per_node gpu \
      --nnodes $WORLD_SIZE \
      --node_rank $RANK \
      --master_addr $MASTER_ADDR \
      --master_port $MASTER_PORT benchmark/kernels/all_reduce/benchmark_mscclpp.py

- template: stop.yml
  parameters:
    subscription: ${{ parameters.subscription }}
    vmssName:     ${{ parameters.vmssName }}