parameters:
- name: subscription
  type: string
- name: vmssName
  type: string
- name: platform
  type: string
  default: 'cuda'
- name: gpuArch
  type: string

steps:
- template: deploy.yml
  parameters:
    subscription:     ${{ parameters.subscription }}
    vmssName:         ${{ parameters.vmssName }}
    platform:         ${{ parameters.platform }}
    gpuArch:          ${{ parameters.gpuArch }}
    deployArgs:       'single-node-test true ${{ parameters.platform }}'


- template: run-remote-task.yml
  parameters:
    name: ExecutorTest
    displayName: Run executor tests
    remoteScript: |
      python3 -m pip install .
      PLANS_DIR=/root/mscclpp/test/executor-tests/execution-plans
      TEST_SCRIPT=/root/mscclpp/python/test/executor_test.py
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/transfer_pack.json --size 32M --in_place
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/transfer_pack_tbg.json --size 32M --in_place
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/reduce.json --size 32M --in_place
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/reduce_tbg.json --size 32M --in_place
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/reduce_pack.json --size 32M --in_place
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/reduce_pack_tbg.json --size 32M --in_place
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/reduce_nvls.json --size 32M --in_place
      mpirun -np 2 --allow-run-as-root python3 $TEST_SCRIPT -path $PLANS_DIR/reduce_nvls_pipeline.json --size 32M --in_place

- template: stop.yml
  parameters:
    subscription: ${{ parameters.subscription }}
    vmssName:     ${{ parameters.vmssName }}
