parameters:
- name: subscription
  type: string
- name: vmssName
  type: string
- name: gpuArch
  type: string

steps:
- template: deploy.yml
  parameters:
    subscription:     ${{ parameters.subscription }}
    vmssName:         ${{ parameters.vmssName }}
    gpuArch:          ${{ parameters.gpuArch }}
    cmakeArgs:        '-DMSCCLPP_USE_IB=OFF'
    deployArgs:       'single-node-test false'

- template: run-remote-task.yml
  parameters:
    name: UnitTests
    displayName: Run mscclpp unit tests
    remoteScript: |
      ./build/bin/unit_tests

- template: run-remote-task.yml
  parameters:
    name: MpUnitTests
    displayName: Run mscclpp multi-process unit tests
    remoteScript: |
      mpirun --allow-run-as-root -tag-output -np 2 ./build/bin/mp_unit_tests
      mpirun --allow-run-as-root -tag-output -np 4 ./build/bin/mp_unit_tests
      mpirun --allow-run-as-root -tag-output -np 8 ./build/bin/mp_unit_tests

- template: run-remote-task.yml
  parameters:
    name: PyTests
    displayName: Run pytests
    remoteScript: |
      mpirun --allow-run-as-root -tag-output -x MSCCLPP_HOME=/root/mscclpp -x MSCCLPP_DISABLE_IB_TESTS=1 -np 8 python3 -m pytest ./python/test/test_mscclpp.py -x

- template: run-remote-task.yml
  parameters:
    name: StopContainer
    displayName: Stop existing container
    runRemoteArgs: '--no-docker --no-log'
    remoteScript: |
      sudo docker stop mscclpp-test || true
      sudo docker rm mscclpp-test || true

- task: Bash@3
  displayName: Remove generated SSH key files
  inputs:
    targetType: 'inline'
    script: |
      rm -f $(System.DefaultWorkingDirectory)/sshkey $(System.DefaultWorkingDirectory)/sshkey.pub
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  
- task: Bash@3
  name: BuildWithIb
  displayName: Rebuild with IB
  inputs:
    targetType: 'inline'
    script: |
      set -e
      rm -rf build
      mkdir -p build && cd build
      cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DMSCCLPP_BYPASS_GPU_CHECK=ON \
        -DMSCCLPP_USE_CUDA=ON \
        -DMSCCLPP_BUILD_TESTS=ON \
        -DMSCCLPP_GPU_ARCHS=${{ parameters.gpuArch }} ..
      make -j
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Bash@3
  name: DeployTestEnvWithIb
  displayName: Deploy Test Env (with IB build)
  inputs:
    targetType: filePath
    filePath: test/deploy/deploy.sh
    arguments: single-node-test false
    workingDirectory: $(System.DefaultWorkingDirectory)

- template: run-remote-task.yml
  parameters:
    name: PyTestsWithIbBuildDisableIb
    displayName: Run pytests (IB build, IB tests disabled)
    remoteScript: |
      mpirun --allow-run-as-root -tag-output -x MSCCLPP_HOME=/root/mscclpp -x MSCCLPP_DISABLE_IB_TESTS=1 -np 8 python3 -m pytest ./python/test/test_mscclpp.py -x

- template: stop.yml
  parameters:
    subscription: ${{ parameters.subscription }}
    vmssName:     ${{ parameters.vmssName }}
