parameters:
- name: subscription
  type: string
- name: vmssName
  type: string
- name: platform
  type: string
  default: 'cuda'
- name: gpuArch
  type: string

steps:
- template: deploy.yml
  parameters:
    subscription:     ${{ parameters.subscription }}
    vmssName:         ${{ parameters.vmssName }}
    platform:         ${{ parameters.platform }}
    gpuArch:          ${{ parameters.gpuArch }}
    deployArgs:       'single-node-test true ${{ parameters.platform }}'


- template: run-remote-task.yml
  parameters:
    name: UnitTests
    displayName: Run mscclpp unit tests
    remoteScript: |
      ./build/bin/unit_tests

- template: run-remote-task.yml
  parameters:
    name: MpUnitTests
    displayName: Run mscclpp multi-process unit tests
    remoteScript: |
      mpirun --allow-run-as-root -tag-output -np 2 ./build/bin/mp_unit_tests
      mpirun --allow-run-as-root -tag-output -np 4 ./build/bin/mp_unit_tests
      mpirun --allow-run-as-root -tag-output -np 8 ./build/bin/mp_unit_tests

- template: run-remote-task.yml
  parameters:
    name: PyTests
    displayName: Run pytests
    remoteScript: |
      mpirun --allow-run-as-root -tag-output -x MSCCLPP_HOME=/root/mscclpp -x GPU_MAX_HW_QUEUES=8 -np 8 python3 -m pytest ./python/test/test_mscclpp.py -x
      mpirun --allow-run-as-root -tag-output -x MSCCLPP_HOME=/root/mscclpp -x -np 8 python3 -m pytest ./python/test/test_fp8_accum.py -x

- template: stop.yml
  parameters:
    subscription: ${{ parameters.subscription }}
    vmssName:     ${{ parameters.vmssName }}
