parameters:
- name: subscription
  type: string
- name: vmssName
  type: string
- name: platform
  type: string
  default: 'cuda'
- name: gpuArch
  type: string

steps:
- template: deploy.yaml
  parameters:
    subscription:     ${{ parameters.subscription }}
    vmssName:         ${{ parameters.vmssName }}
    platform:         ${{ parameters.platform }}
    gpuArch:          ${{ parameters.gpuArch }}
    deployArgs:       'single-node-test true ${{ parameters.platform }}'


- task: Bash@3
  name: UnitTests
  displayName: Run mscclpp unit tests
  inputs:
    targetType: inline
    script: |
      test/deploy/run-remote.sh '\
        ./build/bin/unit_tests'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Bash@3
  name: MpUnitTests
  displayName: Run mscclpp multi-process unit tests
  inputs:
    targetType: 'inline'
    script: |
      test/deploy/run-remote.sh '\
        mpirun --allow-run-as-root -tag-output -np 2 ./build/bin/mp_unit_tests; \
        mpirun --allow-run-as-root -tag-output -np 4 ./build/bin/mp_unit_tests; \
        mpirun --allow-run-as-root -tag-output -np 8 ./build/bin/mp_unit_tests'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Bash@3
  name: PyTests
  displayName: Run pytests
  inputs:
    targetType: inline
    script: |
      test/deploy/run-remote.sh '\
        mpirun --allow-run-as-root -tag-output -x MSCCLPP_HOME=/root/mscclpp -x GPU_MAX_HW_QUEUES=8 -np 8 python3 -m pytest ./python/test/test_mscclpp.py -x'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- template: stop.yaml
  parameters:
    subscription: ${{ parameters.subscription }}
    vmssName:     ${{ parameters.vmssName }}
