trigger:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - .devcontainer/**
    - .github/**
    - docker/**
    - docs/**
    - '**/*.md'

pr:
  branches:
    include:
    - main
    - release/*
  drafts: false
  paths:
    exclude:
      - .devcontainer/**
      - .github/**
      - docker/**
      - docs/**
      - '**/*.md'

parameters:
- name: hostEntries
  type: string
  default: |
    10.0.0.10 mscclit-000000
    10.0.0.11 mscclit-000001

jobs:
- job: SGlangTest
  displayName: SGLANG Test
  strategy:
    matrix:
      sglang:
        containerImage: ghcr.io/microsoft/mscclpp/mscclpp:base-sglang-x86_64
        
  pool:
    name: msccl-ci-h100
  container:
    image: $(containerImage)

  steps:
  - template: templates/sglang-test.yml
    parameters:
      subscription:     mscclpp-ci-h100
      vmssName:         mscclpp-h100-ci
      gpuArch:          '90'

- job: SGlangMultiNodeTest
  displayName: SGLANG Multi-Node Test
  strategy:
    matrix:
      sglang:
        containerImage: ghcr.io/microsoft/mscclpp/mscclpp:base-sglang-x86_64

  pool:
    name: mscclpp-it
  container:
    image: $(containerImage)

  steps:
  - template: templates/sglang-multi-test.yml
    parameters:
        subscription:  msccl-it
        vmssName:      mscclit-vmss
        resourceGroup: msccl-IT