trigger:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - .devcontainer/**
    - .github/**
    - docker/**
    - docs/**
    - '**/*.md'

# Do not run multi-nodes-test for PR, we can trigger it manually
pr: none


parameters:
- name: vmssName
  type: string
  default: mscclpp-h100-multinode-ci
- name: hostEntries
  type: string
  default: |
    10.0.0.5 mscclpp-h100-multinode-ci000000
    10.0.0.4 mscclpp-h100-multinode-ci000001

jobs:
- job: MultiNodesTest
  displayName: Multi nodes test
  strategy:
    matrix:
      cuda12:
        containerImage: ghcr.io/microsoft/mscclpp/mscclpp:base-dev-cuda12.9
  pool:
    name: mscclpp-multi-node
  container:
    image: $[ variables['containerImage'] ]

  steps:
  - task: Bash@3
    displayName: Add HostEntry
    inputs:
      targetType: 'inline'
      script: |
        ENTRY="${{ parameters.hostEntries }}"
        if ! grep -qxF "$ENTRY" /etc/hosts; then
          echo "Adding to /etc/hosts"
          echo "$ENTRY" | sudo tee -a /etc/hosts
        else
          echo "Entry already exists, nothing to do."
        fi

  - task: Bash@3
    displayName: Generate deploy files
    inputs:
      targetType: 'inline'
      script: |
        set -e
        VMSS="${{ parameters.vmssName }}"
        DEPLOY_DIR="$(System.DefaultWorkingDirectory)/test/deploy"
        NODE0="${VMSS}000000"
        NODE1="${VMSS}000001"

        echo "Host ${NODE0}
          Port 22345
          IdentityFile /root/mscclpp/sshkey
          StrictHostKeyChecking no
        Host ${NODE1}
          Port 22345
          IdentityFile /root/mscclpp/sshkey
          StrictHostKeyChecking no" > "${DEPLOY_DIR}/config"

        echo "azureuser@${NODE0}
        azureuser@${NODE1}" > "${DEPLOY_DIR}/hostfile"

        echo "${NODE0}
        ${NODE1}" > "${DEPLOY_DIR}/hostfile_mpi"

  - template: templates/deploy.yml
    parameters:
      subscription:  mscclpp-ci-h100
      vmssName:      ${{ parameters.vmssName }}
      resourceGroup: mscclpp
      gpuArch:       '90'

  - template: templates/run-remote-task.yml
    parameters:
      name: RunMscclppTest
      displayName: Run multi-nodes mscclpp-test
      runRemoteArgs: '--hostfile $(System.DefaultWorkingDirectory)/test/deploy/hostfile --host ${{ parameters.vmssName }}000000 --user azureuser'
      remoteScript: |
        bash /root/mscclpp/test/deploy/run_tests.sh mscclpp-test

  - template: templates/run-remote-task.yml
    parameters:
      name: RunMultiNodeUnitTest
      displayName: Run multi-nodes unit tests
      runRemoteArgs: '--hostfile $(System.DefaultWorkingDirectory)/test/deploy/hostfile --host ${{ parameters.vmssName }}000000 --user azureuser'
      remoteScript: |
        bash /root/mscclpp/test/deploy/run_tests.sh mp-ut

  - template: templates/run-remote-task.yml
    parameters:
      name: RunMultiNodePythonTests
      displayName: Run multi-nodes python tests
      runRemoteArgs: '--hostfile $(System.DefaultWorkingDirectory)/test/deploy/hostfile --host ${{ parameters.vmssName }}000000 --user azureuser'
      remoteScript: |
        bash /root/mscclpp/test/deploy/run_tests.sh pytests

  - template: templates/run-remote-task.yml
    parameters:
      name: RunMultiNodePythonBenchmark
      displayName: Run multi-nodes python benchmark
      runRemoteArgs: '--hostfile $(System.DefaultWorkingDirectory)/test/deploy/hostfile --host ${{ parameters.vmssName }}000000 --user azureuser'
      remoteScript: |
        bash /root/mscclpp/test/deploy/run_tests.sh py-benchmark

  - template: templates/stop.yml
    parameters:
      subscription:  mscclpp-ci-h100
      vmssName:      ${{ parameters.vmssName }}
      resourceGroup: mscclpp
