trigger:
- main
- release/*

pr:
  branches:
    include:
    - main
    - release/*
  drafts: false

jobs:
- job: NcclTestA100
  displayName: Run MSCCLPP over NCCL Test (A100)
  pool:
    name: msccl-ci

  strategy:
    matrix:
      cuda11:
        containerImage: ghcr.io/microsoft/mscclpp/mscclpp:base-dev-cuda11.8
      cuda12:
        containerImage: ghcr.io/microsoft/mscclpp/mscclpp:base-dev-cuda12.4

  container:
    image: $(containerImage)

  steps:
  - template: templates/nccl-test.yaml
    parameters:
      subscription:     mscclpp-ci
      sshKeySecureFile: mscclpp.pem
      containerName:    mscclpp-test
      hostfilePath:     $(System.DefaultWorkingDirectory)/mscclpp/test/deploy/hostfile_ci