name: Docs Build

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Fetch full history for accurate version info
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen=1.9.1-* graphviz
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          cd docs
          rm -rf doxygen _build py_api
          doxygen
          make multiversion
          touch _build/html/.nojekyll
