name: Docs Build

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          # Fetch full history for accurate version info
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen=1.9.1-* graphviz
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          cd docs
          rm -rf doxygen _build py_api
          doxygen
          make multiversion
          touch _build/html/.nojekyll
