name: Lint

on:
  pull_request:
    branches:
      - '**'

jobs:
  cpplint:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install ClangFormat
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Run cpplint
      run: bash ./tools/lint.sh cpp dry

  pylint:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3

    - name: Install Python dependencies
      run: python3 -m pip install black

    - name: Run black
      run: bash ./tools/lint.sh py dry

  spelling:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Download misspell
      run: |
        curl -L https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz -o /tmp/misspell_0.3.4_linux_64bit.tar.gz
        tar -xzf /tmp/misspell_0.3.4_linux_64bit.tar.gz -C .

    - name: Check spelling
      run: |
        ./misspell -error .
