name: Lint

on:
  pull_request:
    branches:
      - '**'

jobs:
  cpplint:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Install ClangFormat
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Run cpplint
      run: bash ./tools/lint.sh cpp dry

  pylint:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: 3

    - name: Install Python dependencies
      run: python3 -m pip install black

    - name: Run black
      run: bash ./tools/lint.sh py dry

  spelling:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out Git repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Download misspell
      run: |
        curl -L https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz -o /tmp/misspell_0.3.4_linux_64bit.tar.gz
        tar -xzf /tmp/misspell_0.3.4_linux_64bit.tar.gz -C .

    - name: Check spelling
      run: |
        ./misspell -error .
