name: Update Version
on:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - 'VERSION'

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Update Version in Files
        run: |
          VERSION=${{ env.VERSION }}
          sed -i "s/^release = \".*\"/release = \"v${VERSION}\"/" docs/conf.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CITATION.cff docs/conf.py || true
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Update version to ${{ env.VERSION }}"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
